### ISSUE TITLE
Saving configs broken

### ISSUE THREAD

**Issue by Jamesfle** [AdriaanBoshoff/The-Forest-Server-Manager#6]
Tried to use the manager after updating and verifying the files. The server did not show up when i started it and tried to join in game. I changed the configs again and saved, still nope. I opened the config.yml and it wasnt the settings i had put at all. So i deleted the entire folder, downloaded The Forest Server Manager again and created a new server. Changed all the configs, went to see what the config.yml said and there was no file??? However the server did now show up. I think this is what is happening to a lot of others on the Steam Forums.

**Comment by AdriaanBoshoff** [comment]
TFSM has no config file you should edit. It's designed to do everything from within the GUIand work with oxidemod. Editing the config.yml won't do anything.
