### ISSUE TITLE
Vegetarian Mode

### ISSUE THREAD

**Issue by Vandyl** [AdriaanBoshoff/The-Forest-Server-Manager#7]
Using the Server Manager, I had turned on vegetarian mode for the server. Everything is running fine, minus the cannibals coming out during the day. I'm not sure how to fix this so that the vegetarian mode works much like when you do it through the game. Restarting server did not fix it either.

**Comment by AdriaanBoshoff** [comment]
Please don't post stuff without googling first. It's annoying. Just by googling "The Forest Dedicated Server" you can find the following in the first link.

-veganmode // Enable the vegan mode cheat (no enemies)
-vegetarianmode // Enable the vegetarian mode cheat (no enemies during daytime)

**Comment by AdriaanBoshoff** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=907906289

**Comment by Vandyl** [comment]
Before you get annoyed, I have googled it. I have the mode enabled via my game menu as well as through the program to host it, using the options given. I have done both modes and neither work. I posted in hopes that I could get assistance with the program in order to enable the mode as the other options were not working for me and I could not find anything via google. Ive already lost progress trying to get the program option to work. No where does it say if I can somehow use the black window to do it with the program itself, since it stems from the program. That is why I posted.

On Tue, Dec 5, 2017 at 11:26 AM, Adriaan Boshoff
<notifications@github.com> wrote:

Please don't post stuff without googling first. It's annoying. Just by googling "The Forest Dedicated Server" you can find the following in the first link.

-veganmode // Enable the vegan mode cheat (no enemies)
-vegetarianmode // Enable the vegetarian mode cheat (no enemies during daytime)
